name: User Admin CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: user-admin

jobs:
  tests:
    name: Testes de Sistema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Starts Api Server
        run: |
          npm ci --prefix ../user-api
          npm ci --prefix ../user-api run start
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

  lint:
    name: Análise estática
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: user-api/package-lock.json
      - run: npm ci
      - run: npm run lint

  vulnerability:
    name: Teste de Vulnerabilidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: user-api/package-lock.json
      - run: npm ci
      - run: npm audit --production